FROM ubuntu:20.10
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get -y update
RUN apt-get -y install flex bison make libboost-all-dev libgsl-dev ghc git vim valgrind build-essential

RUN g++ --version

RUN git clone --branch master https://github.com/jlab/gapc
WORKDIR gapc
RUN ./configure
RUN make -j 4
RUN make install

RUN make test-unit -j 4

WORKDIR testdata/grammar
RUN ../../gapc rnashapesmfe.gap -i mfeppshape --subopt

# build image:
#sudo docker build -t gapc_20.10 -f docker/dockerfile_20.10 .

# run image interactively with mounted host volumne:
#sudo docker run -v "/Daten/Git/jlab/gapc:/GAP" -it gapc_20.10  /bin/bash
