FROM ubuntu:14.04
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get -y update
RUN apt-get -y install flex bison make libboost-all-dev libgsl0-dev ghc git vim valgrind build-essential

RUN g++ --version

RUN git clone --branch master https://github.com/jlab/gapc
WORKDIR gapc
RUN ./configure
RUN sed -E "s/^CXXFLAGS =  -O3  /CXXFLAGS =  -O3 -std=c\+\+11 /" -i config.mf
RUN make -j 4
#RUN make install

#RUN make test-unit -j 4

#WORKDIR testdata/grammar
#RUN ../../gapc rnashapesmfe.gap -i mfeppshape --subopt

# build image:
#sudo docker build -t gapc_14.04 -f docker/dockerfile_14.04 .

# run image interactively with mounted host volumne:
#sudo docker run -v "/Daten/Git/jlab/gapc:/GAP" -it gapc_14.04  /bin/bash
