#!/bin/sh


set -e
set -u

LC_ALL=C

if [ $# != 6 ]; then
  echo $0 prog exact-file mse max-error precision-2 input
exit 23
fi

PROG=$1
EXACT=$2
REF_MSE=$3
MAX_ERROR=$4
PREC=$5
INPUT=$6
PREF=check_shape


$PROG $INPUT > $PREF.log

awk -F\; '/^0;150;0;150;/ { print $5, $6, $7; } ' $PREF.log > t
cp t $PREF.log


if [ "$PREC" = "2" ]; then
grep '0\.0\?0\?[1-9]' $PREF.log | cut -d' ' -f 1,3 | sort > $PREF.mfe.log
grep '0\.0\?0\?[1-9]' $EXACT | cut -d' ' -f 1,3 | sort > $PREF.mfe.old.log
else
grep '0\.0\?[1-9]' $PREF.log | cut -d' ' -f 1,3 | sort > $PREF.mfe.log
grep '0\.0\?[1-9]' $EXACT | cut -d' ' -f 1,3 | sort > $PREF.mfe.old.log
fi

diff -u $PREF.mfe.old.log $PREF.mfe.log

MSE=`awk '/\[/ { if (!f[FILENAME]) f[FILENAME]=1+x++;
            if (f[FILENAME]==1) { a[$1]+=$2; sum_a++; }
               else {b[$1]+=$2; sum_b++;} }
          END { for (i in a) z[i] = 1;
                for (i in b) z[i] = 1;
                for (i in z) err+=(a[i]-b[i])^2;
                sum=sum_a<sum_b?sum_b:sum_a;
                print err/sum; }' $EXACT $PREF.log`
../../fp_eq $MSE $REF_MSE $MAX_ERROR



