#line 2 "src/lexer.cc"

#line 4 "src/lexer.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[285] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   70,   68,   63,   61,   67,   62,   49,   54,
       60,   68,   57,   60,   60,   60,   64,   60,   60,   60,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   60,   63,   62,   66,
       37,   36,   40,   42,   41,   55,   56,   58,   59,   34,
       33,   69,   34,   63,   61,   62,   44,   47,   50,   51,
       52,    0,   53,   38,   35,    0,   64,   66,   45,   43,
       46,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   24,   66,   66,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   48,
       63,    0,    0,   62,   66,   37,   40,   39,   55,   58,
        0,   65,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   26,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,    0,   66,   32,    0,   66,   66,   17,   66,   66,
       66,   66,   66,   25,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,    3,
       13,   22,   66,   19,    0,   66,    0,   65,   66,   66,
       14,   30,   66,   66,   66,   66,   66,   66,   66,   66,

        2,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   27,   66,    0,   66,   66,   66,    6,   66,   66,
       66,    4,   66,   66,    1,   66,   66,   66,   23,   28,
       66,   66,   66,   66,   66,   66,    0,   66,    7,   66,
       66,   66,    9,   12,   66,   66,   66,   66,   66,   66,
       66,   66,   66,    0,   31,   11,   29,   66,   15,   66,
       66,   21,   66,   66,   31,   66,   66,    5,   66,   16,
       66,    8,   10,   66,   66,   66,   66,   66,   18,   66,
       66,   66,   20,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    8,    8,    9,   10,    8,
        8,   11,   12,    8,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    8,    8,   17,
       18,   19,    1,    1,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
        8,    1,    8,    8,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   20,   31,   32,   33,   34,
       35,   36,   20,   37,   38,   39,   40,   41,   42,   43,
       44,   20,    8,   45,    8,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[46] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    4,
        5,    1,    1,    6,    1,    6,    1,    1,    1,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    1
    } ;

static yyconst flex_uint16_t yy_base[296] =
    {   0,
        0,   44,  561,  560,   44,   45,  555,  554,  550,  549,
       55,   61,  558,  565,  555,  553,  565,  550,  536,  565,
      565,  544,  565,   41,   54,   39,   55,  534,  533,  532,
      535,   47,   38,   51,   59,   62,   63,   71,   68,   70,
       67,   85,   74,   75,   81,   94,  503,  109,  115,  107,
        0,  565,    0,  565,  532,    0,  565,    0,  565,  565,
      565,  565,    0,  544,  542,  539,  565,  565,  565,  565,
      565,   87,  565,  565,  565,  527,   96,  528,  565,  565,
      565,  108,   80,  112,  117,  113,  116,  118,  119,  114,
      121,  132,  527,  123,  133,  136,  135,  137,  141,  142,

      147,  150,  148,  153,  151,  152,  154,  156,  159,  565,
      183,  187,  506,  188,  167,    0,    0,  565,    0,    0,
      532,  178,  169,  182,  165,  185,  187,  192,  183,  188,
      193,  198,  524,  196,  200,  194,  201,  202,  209,  211,
      212,  214,  219,  216,  222,  224,  228,  225,  230,  227,
      229,  513,  233,  565,  254,  246,  234,  522,  235,  247,
      248,  257,  259,  521,  260,  263,  261,  262,  265,  266,
      268,  267,  269,  270,  271,  276,  272,  277,  278,  520,
      519,  518,  288,  295,  499,  279,  514,  513,  289,  292,
      514,  513,  298,  303,  304,  306,  307,  308,  309,  311,

      512,  313,  314,  320,  315,  318,  321,  322,  325,  323,
      326,  508,  329,  477,  331,  335,  337,  496,  339,  344,
      351,  492,  346,  353,  489,  354,  356,  355,  483,  450,
      357,  358,  359,  361,  360,   37,  438,  362,  448,  363,
      366,  378,  447,  445,  372,  379,  368,  381,  383,  373,
      387,  389,  395,  432,  443,  441,  440,  386,  439,  394,
      400,  402,  399,  403,  565,  404,  405,  437,  413,  436,
      414,  431,  427,  408,  415,  418,  416,  419,  424,  420,
      425,  421,  422,  565,  465,  471,  477,  483,  489,  240,
      495,  501,  507,  513,  519

    } ;

static yyconst flex_int16_t yy_def[296] =
    {   0,
      284,    1,  285,  285,  286,  286,  287,  287,  288,  288,
      289,  289,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  290,  284,  284,  284,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  284,  284,  284,  290,
      291,  284,  292,  284,  284,  293,  284,  294,  284,  284,
      284,  284,  295,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  290,  290,  284,  284,
      284,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  284,
      284,  284,  284,  284,  290,  291,  292,  284,  293,  294,
      295,  284,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  284,  290,  284,  284,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  284,  290,  284,  284,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  284,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  284,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  284,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  284,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,    0,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284

    } ;

static yyconst flex_uint16_t yy_nxt[611] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       21,   24,   25,   21,   26,   27,   28,   29,   30,   31,
       31,   32,   33,   34,   31,   35,   36,   37,   31,   38,
       39,   31,   31,   31,   31,   40,   41,   42,   43,   44,
       45,   46,   31,   31,   47,   48,   54,   54,   49,   74,
      284,  284,   69,   75,   55,   55,   61,   62,   70,   61,
      284,   63,   61,   62,  284,   61,   71,   63,   76,   72,
       77,   73,  284,   50,   85,  284,  284,  253,   82,   86,
      284,  284,   87,  284,  284,   88,   83,  284,  284,   84,
       89,   97,   99,  284,  284,  104,   91,   93,  284,   92,

       76,   90,   72,   94,   95,   96,   98,  284,  100,   76,
      111,   77,  106,  112,  101,  107,  112,  105,  125,  114,
      284,  284,  108,  109,  102,  284,  284,  284,  103,  284,
      284,  284,  284,   93,  284,  123,  284,  129,  113,   94,
      115,  126,  127,  124,  113,  284,  284,  128,  284,  284,
      284,  130,  132,  134,  284,  284,  131,  133,  135,  138,
      284,  284,  140,  284,  284,  284,  284,  284,  136,  284,
      137,  139,  284,  144,  143,  146,  142,  148,  284,  141,
      284,  145,  284,  149,  111,  150,  147,  112,  112,  112,
      153,  112,  114,  122,  156,  284,  284,  151,  284,  158,

      284,  284,  136,  155,  137,  284,  284,  284,  160,  284,
      157,  284,  113,  284,  284,  284,  113,  113,  164,  159,
      162,  161,  284,  165,  284,  284,  163,  284,  166,  284,
      172,  167,  284,  169,  168,  284,  171,  284,  284,  170,
      284,  284,  284,  284,  177,   78,  284,  284,  284,  173,
      175,  174,  176,  180,  182,  190,  178,  184,  183,  284,
      284,  284,  181,  179,  186,  187,  187,  191,  189,  188,
      284,  193,  284,  284,  284,  284,  284,  192,  284,  284,
      284,  284,  284,  284,  284,  284,  199,  202,  195,  284,
      284,  284,  284,  196,  194,  198,  197,  208,  200,  204,

      207,  284,  284,  201,  203,  284,  206,  205,  284,  211,
      209,  284,  210,  212,  217,  213,  284,  284,  215,  284,
      284,  284,  284,  218,  284,  216,  284,  284,  284,  223,
      221,  284,  219,  284,  284,  284,  284,  220,  284,  284,
      222,  224,  284,  227,  284,  228,  226,  235,  284,  225,
      284,  230,  284,  233,  231,  238,  239,  284,  229,  284,
      232,  234,  240,  236,  284,  241,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  246,  245,  284,
      250,  284,  244,  242,  229,  284,  284,  255,  243,  247,
      251,  284,  284,  248,  284,  229,  284,  249,  252,  284,

      284,  256,  284,  257,  259,  258,  260,  284,  284,  229,
      229,  262,  284,  284,  263,  284,  284,  284,  284,  261,
      264,  284,  269,  270,  266,  268,  284,  284,  284,  284,
      267,  284,  284,  284,  284,  284,  277,  284,  284,  271,
      284,  272,  273,  278,  284,  275,  282,  274,  276,  284,
      284,  281,  284,  284,  284,  280,  284,  265,  284,  279,
      284,  284,  254,  284,  283,   51,   51,   51,   51,   51,
       51,   53,   53,   53,   53,   53,   53,   56,   56,   56,
       56,   56,   56,   58,   58,   58,   58,   58,   58,   60,
       60,   60,   60,   60,   60,  116,  284,  116,  116,  116,

      116,  117,  284,  117,  117,  284,  117,  119,  119,  284,
      119,  119,  119,  120,  120,  120,  237,  120,  120,  121,
      121,  284,  121,  121,  121,  284,  284,  284,  188,  188,
      214,  284,  284,  284,  284,  284,  185,  284,  154,  152,
      284,  284,  122,   66,   65,   64,  118,  110,  284,   81,
       80,   79,   68,   67,   66,   65,   64,  284,   59,   59,
       57,   57,   52,   52,   13,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284
    } ;

static yyconst flex_int16_t yy_chk[611] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    5,    6,    2,   26,
      236,   33,   24,   26,    5,    6,   11,   11,   24,   11,
       32,   11,   12,   12,   34,   12,   25,   12,   27,   25,
       27,   25,   35,    2,   33,   36,   37,  236,   32,   34,
       41,   39,   34,   40,   38,   34,   32,   43,   44,   32,
       35,   40,   41,   83,   45,   43,   36,   38,   42,   37,

       72,   35,   72,   38,   38,   39,   40,   46,   42,   77,
       48,   77,   44,   48,   42,   45,   49,   43,   83,   49,
       50,   82,   46,   46,   42,   84,   86,   90,   42,   87,
       85,   88,   89,   50,   91,   82,   94,   87,   48,   50,
       50,   84,   85,   82,   49,   92,   95,   86,   97,   96,
       98,   88,   90,   92,   99,  100,   89,   91,   94,   96,
      101,  103,   98,  102,  105,  106,  104,  107,   95,  108,
       95,   97,  109,  102,  101,  104,  100,  106,  125,   99,
      115,  103,  123,  107,  111,  108,  105,  111,  112,  114,
      115,  112,  114,  122,  123,  124,  129,  109,  126,  125,

      127,  130,  115,  122,  115,  128,  131,  136,  127,  134,
      124,  132,  111,  135,  137,  138,  112,  114,  131,  126,
      129,  128,  139,  132,  140,  141,  130,  142,  134,  144,
      139,  135,  143,  136,  135,  145,  138,  146,  148,  137,
      150,  147,  151,  149,  144,  290,  153,  157,  159,  140,
      142,  141,  143,  147,  149,  157,  145,  151,  150,  156,
      160,  161,  148,  146,  153,  155,  155,  159,  156,  155,
      162,  161,  163,  165,  167,  168,  166,  160,  169,  170,
      172,  171,  173,  174,  175,  177,  167,  170,  163,  176,
      178,  179,  186,  165,  162,  166,  165,  176,  168,  172,

      175,  183,  189,  169,  171,  190,  174,  173,  184,  179,
      177,  193,  178,  183,  190,  184,  194,  195,  186,  196,
      197,  198,  199,  193,  200,  189,  202,  203,  205,  198,
      196,  206,  194,  204,  207,  208,  210,  195,  209,  211,
      197,  199,  213,  203,  215,  204,  202,  211,  216,  200,
      217,  206,  219,  209,  207,  215,  216,  220,  205,  223,
      208,  210,  217,  213,  221,  219,  224,  226,  228,  227,
      231,  232,  233,  235,  234,  238,  240,  226,  224,  241,
      233,  247,  223,  220,  231,  245,  250,  238,  221,  227,
      234,  242,  246,  228,  248,  247,  249,  232,  235,  258,

      251,  240,  252,  242,  246,  245,  248,  260,  253,  241,
      251,  250,  263,  261,  252,  262,  264,  266,  267,  249,
      253,  274,  262,  263,  258,  261,  269,  271,  275,  277,
      260,  276,  278,  280,  282,  283,  275,  279,  281,  264,
      273,  266,  267,  276,  272,  271,  281,  269,  274,  270,
      268,  280,  259,  257,  256,  278,  255,  254,  244,  277,
      243,  239,  237,  230,  282,  285,  285,  285,  285,  285,
      285,  286,  286,  286,  286,  286,  286,  287,  287,  287,
      287,  287,  287,  288,  288,  288,  288,  288,  288,  289,
      289,  289,  289,  289,  289,  291,  229,  291,  291,  291,

      291,  292,  225,  292,  292,  222,  292,  293,  293,  218,
      293,  293,  293,  294,  294,  294,  214,  294,  294,  295,
      295,  212,  295,  295,  295,  201,  192,  191,  188,  187,
      185,  182,  181,  180,  164,  158,  152,  133,  121,  113,
       93,   78,   76,   66,   65,   64,   55,   47,   31,   30,
       29,   28,   22,   19,   18,   16,   15,   13,   10,    9,
        8,    7,    4,    3,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/lexer.l"
/* {{{

    This file is part of gapc (GAPC - Grammars, Algebras, Products - Compiler;
      a system to compile algebraic dynamic programming programs)

    Copyright (C) 2008-2011  Georg Sauthoff
         email: gsauthof@techfak.uni-bielefeld.de or gsauthof@sdf.lonestar.org

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

}}} */
#line 25 "src/lexer.l"


#include "parser.hh"

#include "lexer.h"

typedef yy::Parser::token token;

#include <stack>

#include "driver.hh"

namespace scanner {


static Driver *driver;

struct state_t {

state_t()
: offset(0), last_nl(0), filename(0) {}

long offset;
long last_nl;
std::string *filename;

};

state_t state;

static bool first_call = true;

void init(Driver *d)
{
  driver = d;
  state.offset = 0;
  state.last_nl = 0;
  state.filename = driver->filename();
  first_call = true;
}

std::stack<state_t> states;

}


#define YY_USER_ACTION do { \
  yylloc->step(); \
  yylloc->columns(yyleng); \
  scanner::state.offset+=yyleng; \
} while(0);

/* By default yylex returns int, we use token_type.
   Unfortunately yyterminate by default returns 0, which is
   not of token_type.  -> see info bison */
#define yyterminate() return token::END

static void new_line(yy::Parser::location_type *yylloc)
{
  yylloc->lines();
  yylloc->step();
  scanner::state.last_nl = scanner::state.offset;
  yylloc->setOffset(scanner::state.last_nl);
  yylloc->set_file(yyin);
}

/* debug */





#line 794 "src/lexer.cc"

#define INITIAL 0
#define SKIP_LINE 1
#define SKIP_COMMENT 2
#define STRING_QUOTE 3
#define CHAR_QUOTE 4
#define INCLUDE 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 103 "src/lexer.l"


 /* gets pasted in yylex at the beginning */

  yylloc->step();
  yylloc->setOffset(scanner::state.last_nl);
  yylloc->set_file(yyin);

  if (scanner::first_call) {
    scanner::first_call = false;
    return start_symbol;
  }


 /* ------------------------------------------------------------------------ */
 /* keywords */
 /* ------------------------------------------------------------------------ */

#line 1037 "src/lexer.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 284 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 121 "src/lexer.l"
{ return token::IMPORT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 123 "src/lexer.l"
{ return token::INPUT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 125 "src/lexer.l"
{ return token::TYPE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 127 "src/lexer.l"
{ return token::EXTERN; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 129 "src/lexer.l"
{ return token::SIGNATURE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 131 "src/lexer.l"
{ return token::CHOICE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 133 "src/lexer.l"
{ return token::ALGEBRA; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 135 "src/lexer.l"
{ return token::IMPLEMENTS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 137 "src/lexer.l"
{ return token::EXTENDS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 139 "src/lexer.l"
{ return token::PARAMETERS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 141 "src/lexer.l"
{ return token::ALPHABET; }
	YY_BREAK
/* answer { return token::ANSWER; } -> just the return type of axiom alg fn */
case 12:
YY_RULE_SETUP
#line 145 "src/lexer.l"
{ return token::GRAMMAR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 147 "src/lexer.l"
{ return token::USES; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 149 "src/lexer.l"
{ return token::AXIOM; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 151 "src/lexer.l"
{ return token::INSTANCE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 153 "src/lexer.l"
{ return token::TABULATED; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 155 "src/lexer.l"
{ return token::AUTOMATIC; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 157 "src/lexer.l"
{ return token::WITH_OVERLAY; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 159 "src/lexer.l"
{ return token::WITH; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 161 "src/lexer.l"
{ return token::SUCHTHAT_OVERLAY; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 163 "src/lexer.l"
{ return token::SUCHTHAT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 166 "src/lexer.l"
{ return token::VOID; }
	YY_BREAK
/* ------------------------------------------------------------------------ */
/* algebra types */
/* ------------------------------------------------------------------------ */
case 23:
YY_RULE_SETUP
#line 172 "src/lexer.l"
{
     yylval->sval = new std::string(yytext);
     return token::MODE; }
	YY_BREAK
/* ------------------------------------------------------------------------ */
/* statements */
/* ------------------------------------------------------------------------ */
case 24:
YY_RULE_SETUP
#line 180 "src/lexer.l"
{ return token::IF; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 182 "src/lexer.l"
{ return token::ELSE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 184 "src/lexer.l"
{ return token::FOR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 186 "src/lexer.l"
{ return token::WHILE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 188 "src/lexer.l"
{ return token::RETURN; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 190 "src/lexer.l"
{ return token::CONTINUE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 192 "src/lexer.l"
{ return token::BREAK; }
	YY_BREAK
/* ------------------------------------------------------------------------ */
/* include files */
/* ------------------------------------------------------------------------ */
case 31:
YY_RULE_SETUP
#line 198 "src/lexer.l"
{ BEGIN INCLUDE; }
	YY_BREAK

case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 203 "src/lexer.l"
{
  std::string s(yytext);
  std::string t(s.substr(1, s.size()-2));

  scanner::states.push(scanner::state);
  scanner::state = scanner::state_t();
  scanner::state.filename = yylloc->begin.filename = yylloc->end.filename = new std::string(t);

  scanner::driver->push_buffer(t);

  yylloc->set_file(yyin);

  BEGIN INITIAL;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 218 "src/lexer.l"
;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 220 "src/lexer.l"
{  return token::UNEXPECTED_CHARACTER; }
	YY_BREAK

/* ------------------------------------------------------------------------ */
/* comments */
/* ------------------------------------------------------------------------ */
case 35:
YY_RULE_SETUP
#line 229 "src/lexer.l"
{ BEGIN SKIP_LINE; }
	YY_BREAK

case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 232 "src/lexer.l"
{ new_line(yylloc); BEGIN INITIAL; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 233 "src/lexer.l"
;
	YY_BREAK

case 38:
YY_RULE_SETUP
#line 236 "src/lexer.l"
{ BEGIN SKIP_COMMENT; }
	YY_BREAK

case 39:
YY_RULE_SETUP
#line 239 "src/lexer.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 240 "src/lexer.l"
;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 241 "src/lexer.l"
;
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 242 "src/lexer.l"
{ new_line(yylloc); }
	YY_BREAK

/* ------------------------------------------------------------------------ */
/* operators */
/* ------------------------------------------------------------------------ */
case 43:
YY_RULE_SETUP
#line 248 "src/lexer.l"
{ return token::EQ; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 250 "src/lexer.l"
{ return token::NEQ; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 252 "src/lexer.l"
{ return token::LT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 254 "src/lexer.l"
{ return token::GT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 256 "src/lexer.l"
{ return token::AND; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 258 "src/lexer.l"
{ return token::OR; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 260 "src/lexer.l"
{ return token::NOT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 262 "src/lexer.l"
{ return token::INC; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 264 "src/lexer.l"
{ return token::IEQ; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 266 "src/lexer.l"
{ return token::DEC; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 268 "src/lexer.l"
{ return token::DEQ; }
	YY_BREAK
/* ------------------------------------------------------------------------ */
/* chars, strings */
/* ------------------------------------------------------------------------ */
case 54:
YY_RULE_SETUP
#line 274 "src/lexer.l"
{ BEGIN STRING_QUOTE; return yy::Parser::token_type(yytext[0]); }
	YY_BREAK

case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 277 "src/lexer.l"
{  yylval->sval = new std::string(yytext); return token::STRING; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 278 "src/lexer.l"
{ BEGIN INITIAL; return yy::Parser::token_type(yytext[0]); }
	YY_BREAK

case 57:
YY_RULE_SETUP
#line 281 "src/lexer.l"
{ BEGIN CHAR_QUOTE; return yy::Parser::token_type(yytext[0]); }
	YY_BREAK

case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 284 "src/lexer.l"
{ yylval->sval = new std::string(yytext); return token::STRING; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 285 "src/lexer.l"
{ BEGIN INITIAL; return yy::Parser::token_type(yytext[0]); }
	YY_BREAK

/* ------------------------------------------------------------------------ */
/* special characters */
/* ------------------------------------------------------------------------ */
case 60:
YY_RULE_SETUP
#line 292 "src/lexer.l"
{ return yy::Parser::token_type(yytext[0]); }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 294 "src/lexer.l"
{ yylloc->lines(yyleng-1); new_line(yylloc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 296 "src/lexer.l"
;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 298 "src/lexer.l"
{ yylloc->columns(yyleng*8-yyleng); }
	YY_BREAK
/* ------------------------------------------------------------------------ */
/* sval aka string , number ... */
/* ------------------------------------------------------------------------ */
case 64:
YY_RULE_SETUP
#line 303 "src/lexer.l"
{ yylval->sval = new std::string(yytext); return token::NUMBER; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 305 "src/lexer.l"
{
   yylval->sval = new std::string(yytext); return token::FLOAT;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 309 "src/lexer.l"
{ yylval->sval = new std::string(yytext); return token::STRING; }
	YY_BREAK
/* ignore carriage return - stupid windows users ... */
case 67:
YY_RULE_SETUP
#line 312 "src/lexer.l"
;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SKIP_LINE):
case YY_STATE_EOF(SKIP_COMMENT):
case YY_STATE_EOF(STRING_QUOTE):
case YY_STATE_EOF(CHAR_QUOTE):
case YY_STATE_EOF(INCLUDE):
#line 314 "src/lexer.l"
{
  yypop_buffer_state();
  if (!YY_CURRENT_BUFFER)
    yyterminate();
  else {
    assert(!scanner::states.empty());
    scanner::state = scanner::states.top();
    scanner::states.pop();
    yylloc->begin.filename = yylloc->end.filename = scanner::state.filename;
  }
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 326 "src/lexer.l"
{ return token::UNEXPECTED_CHARACTER; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 328 "src/lexer.l"
ECHO;
	YY_BREAK
#line 1514 "src/lexer.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 284);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 328 "src/lexer.l"





