name: pytorch interface

on:
  push:
    branches: [ master, pytorch_interface ]
  pull_request:
    branches: [ master, pytorch_interface ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  gapc_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Update apt
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install flex bison make libboost-all-dev libgsl-dev python3 python3-pip python3-dev
    - name: Install Pytorch and its dependencies
      run: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
    - name: Install ninja for faster module builds
      run: pip3 install ninja
    - name: Checkout truth
      run: git clone --branch derivative_truth https://github.com/jlab/gapc-test-suite.git $GITHUB_WORKSPACE/../gapc-test-suite

    - uses: actions/checkout@v3
    - name: Configure GAPC
      run: ./configure --prefix $GITHUB_WORKSPACE
    - name: Compile GAPC
      run: make -j 2
    - name: Install GAPC
      run: sudo make install

    - name: Test non-batched and batched input
      run: make test-pytorch TRUTH_DIR=$GITHUB_WORKSPACE/../gapc-test-suite/Truth/Regress
